# Generated by Django 3.2.5 on 2022-05-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCancelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField(default='1000-10-10')),
                ('price', models.FloatField(default=0.0)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('requestReason', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userMakingRequest', models.CharField(default='Guest', max_length=100)),
                ('requestReason', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('manager', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buildingName', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(default='', max_length=100)),
                ('cardNumber', models.CharField(default='', max_length=100)),
                ('expiryDate', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('discountRate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultFilm.jpg', upload_to='film_images/')),
                ('title', models.CharField(max_length=100)),
                ('ageRating', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=75)),
                ('teirOneAdvert', models.BooleanField(default=False)),
                ('teirTwoAdvert', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showDate', models.DateField()),
                ('endDate', models.DateField()),
                ('screeningTime', models.TimeField(default=5)),
                ('price', models.FloatField(default=5.55)),
                ('filmId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.film')),
                ('screenId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.screen')),
            ],
        ),
        migrations.CreateModel(
            name='StudentJoinRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('birthDay', models.DateField(default='')),
                ('club', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_clubRep', models.BooleanField(default=False)),
                ('is_Student', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=100)),
                ('ticketType', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField(default='1000-10-10')),
                ('film', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('showingRoom', models.CharField(max_length=100)),
                ('showingDate', models.DateField(default='1000-10-10')),
                ('startTime', models.TimeField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(default='Not Guest', max_length=100)),
                ('phone', models.CharField(default='Not Guest', max_length=100)),
                ('userName', models.CharField(default='Guest', max_length=100)),
                ('cancelInProgress', models.CharField(default='No', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTimeChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('TicketLeft', models.IntegerField()),
                ('showTime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200, unique=True)),
                ('birthDate', models.DateField(default='1000-10-10')),
                ('discountRate', models.IntegerField(default=0)),
                ('credit', models.FloatField(default=0.0)),
                ('is_clubRep', models.BooleanField(default=False)),
                ('is_Student', models.BooleanField(default=False)),
                ('is_CinemaManager', models.BooleanField(default=False)),
                ('is_AccountsManager', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uweflixapp.club')),
                ('creditCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.creditcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
